import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FooterWave from './components/common/footerWave'
import { Navbar } from './components/common/navbar'
import { CTALanding } from './components/landing/ctaLanding'
import { LandingLayout } from './components/layout/landingLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingLayout>

        <Navbar />
        <CTALanding />

      </LandingLayout>

    </>
  )
}
